create view AppWithBrief as
    select
        `App`.`Id` `Id`,
        `App`.`CensoredName` `CensoredName`,
        `App`.`Description` `Description`,
        `App`.`LargeIconUrl` `LargeIconUrl`,
        `App`.`SellerName` `SellerName`,
        `App`.`SellerViewUrl` `SellerViewUrl`,
        `App`.`ReleaseNotes` `ReleaseNotes`,
        `App`.`ContentAdvisoryRating` `ContentAdvisoryRating`,
        `App`.`ContentRating` `ContentRating`,
        `App`.`AverageUserRating` `AverageUserRating`,
        `App`.`UserRatingCount` `UserRatingCount`,
        `App`.`Languages` `Languages`,
        `App`.`Categories` `Categories`,
        `App`.`ScreenshotUrls` `ScreenshotUrls`,
        `App`.`IPadScreenshotUrls` `IPadScreenshotUrls`,
        `AppBrief`.`DeveloperId` `Brief.DeveloperId`,
        `AppBrief`.`DeveloperName` `Brief.DeveloperName`,
        `AppBrief`.`DeveloperViewUrl` `Brief.DeveloperViewUrl`,
        `AppBrief`.`Price` `Brief.Price`,
        `AppBrief`.`Currency` `Brief.Currency`,
        `AppBrief`.`Version` `Brief.Version`,
        `AppBrief`.`ReleaseDate` `Brief.ReleaseDate`,
        `AppBrief`.`Name` `Brief.Name`,
        `AppBrief`.`Introduction` `Brief.Introduction`,
        `AppBrief`.`ReleaseNotes` `Brief.ReleaseNotes`,
        `AppBrief`.`PrimaryCategory` `Brief.PrimaryCategory`,
        `AppBrief`.`ViewUrl` `Brief.ViewUrl`,
        `AppBrief`.`IconUrl` `Brief.IconUrl`,
        `AppBrief`.`FileSize` `Brief.FileSize`,
        `AppBrief`.`AverageUserRatingForCurrentVersion` `Brief.AverageUserRatingForCurrentVersion`,
        `AppBrief`.`UserRatingCountForCurrentVersion` `Brief.UserRatingCountForCurrentVersion`,
        `AppBrief`.`SupportedDevices` `Brief.SupportedDevices`,
        `AppBrief`.`Features` `Brief.Features`,
        `AppBrief`.`IsGameCenterEnabled` `Brief.IsGameCenterEnabled`,
        `AppBrief`.`DeviceType` `Brief.DeviceType`,
        `AppBrief`.`LastValidUpdateTime` `Brief.LastValidUpdateTime`,
        `AppBrief`.`LastValidUpdateType` `Brief.LastValidUpdateType`,
        `AppBrief`.`LastValidUpdateOldValue` `Brief.LastValidUpdateOldValue`,
        `AppBrief`.`LastValidUpdateNewValue` `Brief.LastValidUpdateNewValue`,
        `AppBrief`.`LanguagePriority` `Brief.LanguagePriority`
    from `App` 
    inner join `AppBrief` 
        on `AppBrief`.`Id` = `App`.`Id`;