create view RevokedAppWithBrief as
    select
        `RevokedApp`.`Id` `Id`,
        `RevokedApp`.`CensoredName` `CensoredName`,
        `RevokedApp`.`Description` `Description`,
        `RevokedApp`.`LargeIconUrl` `LargeIconUrl`,
        `RevokedApp`.`SellerName` `SellerName`,
        `RevokedApp`.`SellerViewUrl` `SellerViewUrl`,
        `RevokedApp`.`ReleaseNotes` `ReleaseNotes`,
        `RevokedApp`.`ContentAdvisoryRating` `ContentAdvisoryRating`,
        `RevokedApp`.`ContentRating` `ContentRating`,
        `RevokedApp`.`AverageUserRating` `AverageUserRating`,
        `RevokedApp`.`UserRatingCount` `UserRatingCount`,
        `RevokedApp`.`Languages` `Languages`,
        `RevokedApp`.`Categories` `Categories`,
        `RevokedApp`.`ScreenshotUrls` `ScreenshotUrls`,
        `RevokedApp`.`IPadScreenshotUrls` `IPadScreenshotUrls`,
        `RevokedAppBrief`.`DeveloperId` `Brief.DeveloperId`,
        `RevokedAppBrief`.`DeveloperName` `Brief.DeveloperName`,
        `RevokedAppBrief`.`DeveloperViewUrl` `Brief.DeveloperViewUrl`,
        `RevokedAppBrief`.`Price` `Brief.Price`,
        `RevokedAppBrief`.`Currency` `Brief.Currency`,
        `RevokedAppBrief`.`Version` `Brief.Version`,
        `RevokedAppBrief`.`ReleaseDate` `Brief.ReleaseDate`,
        `RevokedAppBrief`.`Name` `Brief.Name`,
        `RevokedAppBrief`.`Introduction` `Brief.Introduction`,
        `RevokedAppBrief`.`ReleaseNotes` `Brief.ReleaseNotes`,
        `RevokedAppBrief`.`PrimaryCategory` `Brief.PrimaryCategory`,
        `RevokedAppBrief`.`ViewUrl` `Brief.ViewUrl`,
        `RevokedAppBrief`.`IconUrl` `Brief.IconUrl`,
        `RevokedAppBrief`.`FileSize` `Brief.FileSize`,
        `RevokedAppBrief`.`AverageUserRatingForCurrentVersion` `Brief.AverageUserRatingForCurrentVersion`,
        `RevokedAppBrief`.`UserRatingCountForCurrentVersion` `Brief.UserRatingCountForCurrentVersion`,
        `RevokedAppBrief`.`SupportedDevices` `Brief.SupportedDevices`,
        `RevokedAppBrief`.`Features` `Brief.Features`,
        `RevokedAppBrief`.`IsGameCenterEnabled` `Brief.IsGameCenterEnabled`,
        `RevokedAppBrief`.`DeviceType` `Brief.DeviceType`,
        `RevokedAppBrief`.`LastValidUpdateTime` `Brief.LastValidUpdateTime`,
        `RevokedAppBrief`.`LastValidUpdateType` `Brief.LastValidUpdateType`,
        `RevokedAppBrief`.`LastValidUpdateOldValue` `Brief.LastValidUpdateOldValue`,
        `RevokedAppBrief`.`LastValidUpdateNewValue` `Brief.LastValidUpdateNewValue`,
        `RevokedAppBrief`.`LanguagePriority` `Brief.LanguagePriority`,
        `RevokedAppBrief`.`RevokeTime` `Brief.RevokeTime`
    from `RevokedApp` 
    inner join `RevokedAppBrief` 
        on `RevokedAppBrief`.`Id` = `RevokedApp`.`Id`;